### ISSUE TITLE
pretrain model 사용 관련 질문입니다.

### ISSUE THREAD

**Issue by azure-in-lab** [AnimalDatathonKorea/adk2021#2]
안녕하세요 pretrain 관련 질문이 생겨서 글 남깁니다.

Pre-trained model 사용 가능이라고 나와 있는데
범용적인 모델만 이용이 가능한지 custom 모델을 pre-train 시켜서 사용이 가능한지 궁금합니다.
또한 custom 모델이 가능하다면 pre-train 데이터에 대한 제한은 따로 없는 것인지 알고싶습니다.

**Comment by Animal-Datathon-korea** [comment]
안녕하세요. Animal Datathon Korea 2021 운영사무국입니다.

문의 주신 내용 답변 드립니다.

> 행사에서 사용하는 모델 및 데이터에 대해서는 제한을 두고 있지 않습니다.
> 따라서 범용적인 모델 뿐만 아니라 custom 모델도 사용 가능하고
> pre-train data들에 대해서도 제한 없이 사용 가능합니다.
> 
> 추가적으로, 행사 진행은 주최측에서 제공된 서버에서 진행 될 예정이기 때문에
> custom 모델을 사용하기 위한 패키지 설치는 행사 시작 전 사전 오픈 기간에 준비를 해야 합니다.

감사합니다.
