### ISSUE TITLE
참가신청서에 '수행역량'은 무엇을 쓰는 건가요?

### ISSUE THREAD

**Issue by yskim0** [AnimalDatathonKorea/adk2021#8]
안녕하세요!
1. 참가신청서에 '수행역량'은 어떤 내용들을 쓰는 건가요?
2. 참가신청서에 '내용요약' 1000자라고 되어 있는데 공백 포함인지 미포함인지 궁금합니다.
감사합니다!

**Comment by Animal-Datathon-korea** [comment]
안녕하세요. Animal Datathon Korea 2021 운영사무국입니다.

문의 주신 내용 답변 드립니다.

참가신청서 수행역량은 기존에 참여하였던 대회 경험이나 AI모델 개발역량 등을 작성하시면 되고,
내용요약은 이번 대회에 참여하여 수행할 내용에 대한 요약을 공백 미포함 1,000자 내외로 작성하시면 됩니다.

감사합니다.
